// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByPM1Yj1ZoCCjXmvK-pf88A0bT5hSPyhI',
    appId: '1:651167476051:web:23d5e958a2c9231649d9a6',
    messagingSenderId: '651167476051',
    projectId: 'evently-app-3fde3',
    authDomain: 'evently-app-3fde3.firebaseapp.com',
    storageBucket: 'evently-app-3fde3.firebasestorage.app',
    measurementId: 'G-P13G088ZGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdAw32bZO7JYcP7Fq6plcm4OG5nxUSbts',
    appId: '1:651167476051:android:47ea9fa488cf7c5a49d9a6',
    messagingSenderId: '651167476051',
    projectId: 'evently-app-3fde3',
    storageBucket: 'evently-app-3fde3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxrU_lboQX2czAkacIlPUkuwEJ6jLALDY',
    appId: '1:651167476051:ios:de683a526bdc2e7d49d9a6',
    messagingSenderId: '651167476051',
    projectId: 'evently-app-3fde3',
    storageBucket: 'evently-app-3fde3.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxrU_lboQX2czAkacIlPUkuwEJ6jLALDY',
    appId: '1:651167476051:ios:de683a526bdc2e7d49d9a6',
    messagingSenderId: '651167476051',
    projectId: 'evently-app-3fde3',
    storageBucket: 'evently-app-3fde3.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByPM1Yj1ZoCCjXmvK-pf88A0bT5hSPyhI',
    appId: '1:651167476051:web:0fc919b288b05b3d49d9a6',
    messagingSenderId: '651167476051',
    projectId: 'evently-app-3fde3',
    authDomain: 'evently-app-3fde3.firebaseapp.com',
    storageBucket: 'evently-app-3fde3.firebasestorage.app',
    measurementId: 'G-JK1HMF4W50',
  );
}
